// Generated by scripts/generate-jsx-types.mjs from @webref/elements, @webref/idl, aria-query, and TypeScript's lib.dom.d.ts.
// Do not edit by hand.
import type { Child } from './index.js'

export type StandardAttributeValue =
  string | number | boolean | null | undefined
export type Style =
  string | Readonly<Record<string, string | number | null | undefined>>
export type EventHandler<E extends Event, T extends globalThis.Element> = (
  event: E & { currentTarget: T },
) => unknown

export interface GeneratedAriaAttributes {
  'aria-activedescendant'?: StandardAttributeValue
  'aria-atomic'?: StandardAttributeValue
  'aria-autocomplete'?: StandardAttributeValue
  'aria-braillelabel'?: StandardAttributeValue
  'aria-brailleroledescription'?: StandardAttributeValue
  'aria-busy'?: StandardAttributeValue
  'aria-checked'?: StandardAttributeValue
  'aria-colcount'?: StandardAttributeValue
  'aria-colindex'?: StandardAttributeValue
  'aria-colspan'?: StandardAttributeValue
  'aria-controls'?: StandardAttributeValue
  'aria-current'?: StandardAttributeValue
  'aria-describedby'?: StandardAttributeValue
  'aria-description'?: StandardAttributeValue
  'aria-details'?: StandardAttributeValue
  'aria-disabled'?: StandardAttributeValue
  'aria-dropeffect'?: StandardAttributeValue
  'aria-errormessage'?: StandardAttributeValue
  'aria-expanded'?: StandardAttributeValue
  'aria-flowto'?: StandardAttributeValue
  'aria-grabbed'?: StandardAttributeValue
  'aria-haspopup'?: StandardAttributeValue
  'aria-hidden'?: StandardAttributeValue
  'aria-invalid'?: StandardAttributeValue
  'aria-keyshortcuts'?: StandardAttributeValue
  'aria-label'?: StandardAttributeValue
  'aria-labelledby'?: StandardAttributeValue
  'aria-level'?: StandardAttributeValue
  'aria-live'?: StandardAttributeValue
  'aria-modal'?: StandardAttributeValue
  'aria-multiline'?: StandardAttributeValue
  'aria-multiselectable'?: StandardAttributeValue
  'aria-orientation'?: StandardAttributeValue
  'aria-owns'?: StandardAttributeValue
  'aria-placeholder'?: StandardAttributeValue
  'aria-posinset'?: StandardAttributeValue
  'aria-pressed'?: StandardAttributeValue
  'aria-readonly'?: StandardAttributeValue
  'aria-relevant'?: StandardAttributeValue
  'aria-required'?: StandardAttributeValue
  'aria-roledescription'?: StandardAttributeValue
  'aria-rowcount'?: StandardAttributeValue
  'aria-rowindex'?: StandardAttributeValue
  'aria-rowspan'?: StandardAttributeValue
  'aria-selected'?: StandardAttributeValue
  'aria-setsize'?: StandardAttributeValue
  'aria-sort'?: StandardAttributeValue
  'aria-valuemax'?: StandardAttributeValue
  'aria-valuemin'?: StandardAttributeValue
  'aria-valuenow'?: StandardAttributeValue
  'aria-valuetext'?: StandardAttributeValue
}

export interface GeneratedAttributes<
  T extends globalThis.Element,
> extends GeneratedAriaAttributes {
  URL?: StandardAttributeValue
  aLink?: StandardAttributeValue
  abbr?: StandardAttributeValue
  aborted?: StandardAttributeValue
  accept?: StandardAttributeValue
  'accept-charset'?: StandardAttributeValue
  acceptCharset?: StandardAttributeValue
  accessKey?: StandardAttributeValue
  accessKeyLabel?: StandardAttributeValue
  action?: StandardAttributeValue
  activation?: StandardAttributeValue
  activeCues?: StandardAttributeValue
  activeElement?: StandardAttributeValue
  actualBoundingBoxAscent?: StandardAttributeValue
  actualBoundingBoxDescent?: StandardAttributeValue
  actualBoundingBoxLeft?: StandardAttributeValue
  actualBoundingBoxRight?: StandardAttributeValue
  addedNodes?: StandardAttributeValue
  align?: StandardAttributeValue
  alinkColor?: StandardAttributeValue
  all?: StandardAttributeValue
  allow?: StandardAttributeValue
  allowFullscreen?: StandardAttributeValue
  alpha?: StandardAttributeValue
  alphabeticBaseline?: StandardAttributeValue
  alt?: StandardAttributeValue
  ancestorOrigins?: StandardAttributeValue
  anchors?: StandardAttributeValue
  angle?: StandardAttributeValue
  animVal?: StandardAttributeValue
  animatedPoints?: StandardAttributeValue
  appCodeName?: StandardAttributeValue
  appName?: StandardAttributeValue
  appVersion?: StandardAttributeValue
  applets?: StandardAttributeValue
  archive?: StandardAttributeValue
  areas?: StandardAttributeValue
  'aria-activedescendant'?: StandardAttributeValue
  'aria-atomic'?: StandardAttributeValue
  'aria-autocomplete'?: StandardAttributeValue
  'aria-braillelabel'?: StandardAttributeValue
  'aria-brailleroledescription'?: StandardAttributeValue
  'aria-busy'?: StandardAttributeValue
  'aria-checked'?: StandardAttributeValue
  'aria-colcount'?: StandardAttributeValue
  'aria-colindex'?: StandardAttributeValue
  'aria-colindextext'?: StandardAttributeValue
  'aria-colspan'?: StandardAttributeValue
  'aria-controls'?: StandardAttributeValue
  'aria-current'?: StandardAttributeValue
  'aria-describedby'?: StandardAttributeValue
  'aria-description'?: StandardAttributeValue
  'aria-details'?: StandardAttributeValue
  'aria-disabled'?: StandardAttributeValue
  'aria-dropeffect'?: StandardAttributeValue
  'aria-errormessage'?: StandardAttributeValue
  'aria-expanded'?: StandardAttributeValue
  'aria-flowto'?: StandardAttributeValue
  'aria-grabbed'?: StandardAttributeValue
  'aria-haspopup'?: StandardAttributeValue
  'aria-hidden'?: StandardAttributeValue
  'aria-invalid'?: StandardAttributeValue
  'aria-keyshortcuts'?: StandardAttributeValue
  'aria-label'?: StandardAttributeValue
  'aria-labelledby'?: StandardAttributeValue
  'aria-level'?: StandardAttributeValue
  'aria-live'?: StandardAttributeValue
  'aria-modal'?: StandardAttributeValue
  'aria-multiline'?: StandardAttributeValue
  'aria-multiselectable'?: StandardAttributeValue
  'aria-orientation'?: StandardAttributeValue
  'aria-owns'?: StandardAttributeValue
  'aria-placeholder'?: StandardAttributeValue
  'aria-posinset'?: StandardAttributeValue
  'aria-pressed'?: StandardAttributeValue
  'aria-readonly'?: StandardAttributeValue
  'aria-relevant'?: StandardAttributeValue
  'aria-required'?: StandardAttributeValue
  'aria-roledescription'?: StandardAttributeValue
  'aria-rowcount'?: StandardAttributeValue
  'aria-rowindex'?: StandardAttributeValue
  'aria-rowindextext'?: StandardAttributeValue
  'aria-rowspan'?: StandardAttributeValue
  'aria-selected'?: StandardAttributeValue
  'aria-setsize'?: StandardAttributeValue
  'aria-sort'?: StandardAttributeValue
  'aria-valuemax'?: StandardAttributeValue
  'aria-valuemin'?: StandardAttributeValue
  'aria-valuenow'?: StandardAttributeValue
  'aria-valuetext'?: StandardAttributeValue
  as?: StandardAttributeValue
  assignedSlot?: StandardAttributeValue
  async?: StandardAttributeValue
  attributeName?: StandardAttributeValue
  attributeNamespace?: StandardAttributeValue
  attributes?: StandardAttributeValue
  audioTracks?: StandardAttributeValue
  autocapitalize?: StandardAttributeValue
  autocomplete?: StandardAttributeValue
  autocorrect?: StandardAttributeValue
  autofocus?: StandardAttributeValue
  autoplay?: StandardAttributeValue
  axis?: StandardAttributeValue
  background?: StandardAttributeValue
  badInput?: StandardAttributeValue
  baseURI?: StandardAttributeValue
  baseVal?: StandardAttributeValue
  behavior?: StandardAttributeValue
  bgColor?: StandardAttributeValue
  blocking?: StandardAttributeValue
  body?: StandardAttributeValue
  booleanValue?: StandardAttributeValue
  border?: StandardAttributeValue
  bubbles?: StandardAttributeValue
  buffered?: StandardAttributeValue
  canGoBack?: StandardAttributeValue
  canGoForward?: StandardAttributeValue
  canIntercept?: StandardAttributeValue
  cancelBubble?: StandardAttributeValue
  cancelable?: StandardAttributeValue
  canvas?: StandardAttributeValue
  caption?: StandardAttributeValue
  cellIndex?: StandardAttributeValue
  cellPadding?: StandardAttributeValue
  cellSpacing?: StandardAttributeValue
  cells?: StandardAttributeValue
  ch?: StandardAttributeValue
  chOff?: StandardAttributeValue
  char?: StandardAttributeValue
  characterSet?: StandardAttributeValue
  charoff?: StandardAttributeValue
  charset?: StandardAttributeValue
  checked?: StandardAttributeValue
  childElementCount?: StandardAttributeValue
  childNodes?: StandardAttributeValue
  cite?: StandardAttributeValue
  class?: StandardAttributeValue
  classList?: StandardAttributeValue
  clear?: StandardAttributeValue
  clientInformation?: StandardAttributeValue
  clonable?: StandardAttributeValue
  closed?: StandardAttributeValue
  closedBy?: StandardAttributeValue
  code?: StandardAttributeValue
  codeBase?: StandardAttributeValue
  codeType?: StandardAttributeValue
  colSpan?: StandardAttributeValue
  collapsed?: StandardAttributeValue
  colno?: StandardAttributeValue
  color?: StandardAttributeValue
  colorSpace?: StandardAttributeValue
  cols?: StandardAttributeValue
  command?: StandardAttributeValue
  commandForElement?: StandardAttributeValue
  commandfor?: StandardAttributeValue
  committed?: StandardAttributeValue
  commonAncestorContainer?: StandardAttributeValue
  compact?: StandardAttributeValue
  compatMode?: StandardAttributeValue
  complete?: StandardAttributeValue
  composed?: StandardAttributeValue
  content?: StandardAttributeValue
  contentDocument?: StandardAttributeValue
  contentEditable?: StandardAttributeValue
  contentType?: StandardAttributeValue
  contentWindow?: StandardAttributeValue
  control?: StandardAttributeValue
  controls?: StandardAttributeValue
  cookie?: StandardAttributeValue
  cookieEnabled?: StandardAttributeValue
  coords?: StandardAttributeValue
  crossOrigin?: StandardAttributeValue
  crossOriginIsolated?: StandardAttributeValue
  cues?: StandardAttributeValue
  currentEntry?: StandardAttributeValue
  currentNode?: StandardAttributeValue
  currentScale?: StandardAttributeValue
  currentScript?: StandardAttributeValue
  currentSrc?: StandardAttributeValue
  currentTarget?: StandardAttributeValue
  currentTime?: StandardAttributeValue
  currentTranslate?: StandardAttributeValue
  customElementRegistry?: StandardAttributeValue
  customElements?: StandardAttributeValue
  customError?: StandardAttributeValue
  cx?: StandardAttributeValue
  cy?: StandardAttributeValue
  data?: StandardAttributeValue
  dataTransfer?: StandardAttributeValue
  dataset?: StandardAttributeValue
  dateTime?: StandardAttributeValue
  declare?: StandardAttributeValue
  decoding?: StandardAttributeValue
  default?: StandardAttributeValue
  defaultChecked?: StandardAttributeValue
  defaultMuted?: StandardAttributeValue
  defaultPlaybackRate?: StandardAttributeValue
  defaultPrevented?: StandardAttributeValue
  defaultSelected?: StandardAttributeValue
  defaultValue?: StandardAttributeValue
  defaultView?: StandardAttributeValue
  defer?: StandardAttributeValue
  delegatesFocus?: StandardAttributeValue
  description?: StandardAttributeValue
  designMode?: StandardAttributeValue
  destination?: StandardAttributeValue
  detail?: StandardAttributeValue
  dir?: StandardAttributeValue
  dirName?: StandardAttributeValue
  direction?: StandardAttributeValue
  disabled?: StandardAttributeValue
  doctype?: StandardAttributeValue
  document?: StandardAttributeValue
  documentElement?: StandardAttributeValue
  documentURI?: StandardAttributeValue
  domain?: StandardAttributeValue
  download?: StandardAttributeValue
  downloadRequest?: StandardAttributeValue
  draggable?: StandardAttributeValue
  dropEffect?: StandardAttributeValue
  duration?: StandardAttributeValue
  dx?: StandardAttributeValue
  dy?: StandardAttributeValue
  effectAllowed?: StandardAttributeValue
  elements?: StandardAttributeValue
  emHeightAscent?: StandardAttributeValue
  emHeightDescent?: StandardAttributeValue
  embeds?: StandardAttributeValue
  enabled?: StandardAttributeValue
  enabledPlugin?: StandardAttributeValue
  encoding?: StandardAttributeValue
  enctype?: StandardAttributeValue
  endContainer?: StandardAttributeValue
  endOffset?: StandardAttributeValue
  endTime?: StandardAttributeValue
  ended?: StandardAttributeValue
  enterKeyHint?: StandardAttributeValue
  entry?: StandardAttributeValue
  entryType?: StandardAttributeValue
  error?: StandardAttributeValue
  event?: StandardAttributeValue
  eventPhase?: StandardAttributeValue
  external?: StandardAttributeValue
  face?: StandardAttributeValue
  fetchPriority?: StandardAttributeValue
  fgColor?: StandardAttributeValue
  filename?: StandardAttributeValue
  files?: StandardAttributeValue
  fillStyle?: StandardAttributeValue
  filter?: StandardAttributeValue
  finished?: StandardAttributeValue
  firstChild?: StandardAttributeValue
  firstElementChild?: StandardAttributeValue
  font?: StandardAttributeValue
  fontBoundingBoxAscent?: StandardAttributeValue
  fontBoundingBoxDescent?: StandardAttributeValue
  fontKerning?: StandardAttributeValue
  fontStretch?: StandardAttributeValue
  fontVariantCaps?: StandardAttributeValue
  for?: StandardAttributeValue
  form?: StandardAttributeValue
  formAction?: StandardAttributeValue
  formData?: StandardAttributeValue
  formEnctype?: StandardAttributeValue
  formMethod?: StandardAttributeValue
  formNoValidate?: StandardAttributeValue
  formTarget?: StandardAttributeValue
  forms?: StandardAttributeValue
  fr?: StandardAttributeValue
  frame?: StandardAttributeValue
  frameBorder?: StandardAttributeValue
  frameElement?: StandardAttributeValue
  frames?: StandardAttributeValue
  from?: StandardAttributeValue
  fx?: StandardAttributeValue
  fy?: StandardAttributeValue
  globalAlpha?: StandardAttributeValue
  globalCompositeOperation?: StandardAttributeValue
  gradientTransform?: StandardAttributeValue
  gradientUnits?: StandardAttributeValue
  hangingBaseline?: StandardAttributeValue
  hardwareConcurrency?: StandardAttributeValue
  hasBeenActive?: StandardAttributeValue
  hasUAVisualTransition?: StandardAttributeValue
  hash?: StandardAttributeValue
  hashChange?: StandardAttributeValue
  head?: StandardAttributeValue
  headers?: StandardAttributeValue
  headingOffset?: StandardAttributeValue
  headingReset?: StandardAttributeValue
  height?: StandardAttributeValue
  hidden?: StandardAttributeValue
  high?: StandardAttributeValue
  history?: StandardAttributeValue
  host?: StandardAttributeValue
  hostname?: StandardAttributeValue
  href?: StandardAttributeValue
  hreflang?: StandardAttributeValue
  hspace?: StandardAttributeValue
  'http-equiv'?: StandardAttributeValue
  httpEquiv?: StandardAttributeValue
  id?: StandardAttributeValue
  ideographicBaseline?: StandardAttributeValue
  imageSizes?: StandardAttributeValue
  imageSmoothingEnabled?: StandardAttributeValue
  imageSmoothingQuality?: StandardAttributeValue
  imageSrcset?: StandardAttributeValue
  images?: StandardAttributeValue
  implementation?: StandardAttributeValue
  inBandMetadataTrackDispatchType?: StandardAttributeValue
  indeterminate?: StandardAttributeValue
  index?: StandardAttributeValue
  inert?: StandardAttributeValue
  info?: StandardAttributeValue
  innerHTML?: StandardAttributeValue
  innerText?: StandardAttributeValue
  inputEncoding?: StandardAttributeValue
  inputMode?: StandardAttributeValue
  integrity?: StandardAttributeValue
  invalidIteratorState?: StandardAttributeValue
  isActive?: StandardAttributeValue
  isConnected?: StandardAttributeValue
  isContentEditable?: StandardAttributeValue
  isMap?: StandardAttributeValue
  isSecureContext?: StandardAttributeValue
  isTrusted?: StandardAttributeValue
  items?: StandardAttributeValue
  key?: StandardAttributeValue
  kind?: StandardAttributeValue
  label?: StandardAttributeValue
  labels?: StandardAttributeValue
  lang?: StandardAttributeValue
  language?: StandardAttributeValue
  languages?: StandardAttributeValue
  lastChild?: StandardAttributeValue
  lastElementChild?: StandardAttributeValue
  lastEventId?: StandardAttributeValue
  lastModified?: StandardAttributeValue
  length?: StandardAttributeValue
  lengthAdjust?: StandardAttributeValue
  letterSpacing?: StandardAttributeValue
  lineCap?: StandardAttributeValue
  lineDashOffset?: StandardAttributeValue
  lineJoin?: StandardAttributeValue
  lineWidth?: StandardAttributeValue
  lineno?: StandardAttributeValue
  link?: StandardAttributeValue
  linkColor?: StandardAttributeValue
  links?: StandardAttributeValue
  list?: StandardAttributeValue
  loading?: StandardAttributeValue
  localName?: StandardAttributeValue
  localStorage?: StandardAttributeValue
  location?: StandardAttributeValue
  locationbar?: StandardAttributeValue
  longDesc?: StandardAttributeValue
  loop?: StandardAttributeValue
  low?: StandardAttributeValue
  lowsrc?: StandardAttributeValue
  marginHeight?: StandardAttributeValue
  marginWidth?: StandardAttributeValue
  markerHeight?: StandardAttributeValue
  markerUnits?: StandardAttributeValue
  markerWidth?: StandardAttributeValue
  matrix?: StandardAttributeValue
  max?: StandardAttributeValue
  maxLength?: StandardAttributeValue
  media?: StandardAttributeValue
  meetOrSlice?: StandardAttributeValue
  menubar?: StandardAttributeValue
  message?: StandardAttributeValue
  method?: StandardAttributeValue
  mimeTypes?: StandardAttributeValue
  min?: StandardAttributeValue
  minLength?: StandardAttributeValue
  miterLimit?: StandardAttributeValue
  mode?: StandardAttributeValue
  multiple?: StandardAttributeValue
  muted?: StandardAttributeValue
  name?: StandardAttributeValue
  namespaceURI?: StandardAttributeValue
  naturalHeight?: StandardAttributeValue
  naturalWidth?: StandardAttributeValue
  navigation?: StandardAttributeValue
  navigationType?: StandardAttributeValue
  navigator?: StandardAttributeValue
  networkState?: StandardAttributeValue
  newState?: StandardAttributeValue
  newURL?: StandardAttributeValue
  newValue?: StandardAttributeValue
  nextElementSibling?: StandardAttributeValue
  nextSibling?: StandardAttributeValue
  noHref?: StandardAttributeValue
  noModule?: StandardAttributeValue
  noResize?: StandardAttributeValue
  noShade?: StandardAttributeValue
  noValidate?: StandardAttributeValue
  noWrap?: StandardAttributeValue
  nodeName?: StandardAttributeValue
  nodeType?: StandardAttributeValue
  nodeValue?: StandardAttributeValue
  nonce?: StandardAttributeValue
  numberOfItems?: StandardAttributeValue
  numberValue?: StandardAttributeValue
  offset?: StandardAttributeValue
  oldState?: StandardAttributeValue
  oldURL?: StandardAttributeValue
  oldValue?: StandardAttributeValue
  opaque?: StandardAttributeValue
  open?: StandardAttributeValue
  opener?: StandardAttributeValue
  optimum?: StandardAttributeValue
  options?: StandardAttributeValue
  orient?: StandardAttributeValue
  orientAngle?: StandardAttributeValue
  orientType?: StandardAttributeValue
  origin?: StandardAttributeValue
  originAgentCluster?: StandardAttributeValue
  oscpu?: StandardAttributeValue
  outerHTML?: StandardAttributeValue
  outerText?: StandardAttributeValue
  ownerDocument?: StandardAttributeValue
  ownerElement?: StandardAttributeValue
  ownerSVGElement?: StandardAttributeValue
  parent?: StandardAttributeValue
  parentElement?: StandardAttributeValue
  parentNode?: StandardAttributeValue
  password?: StandardAttributeValue
  pathLength?: StandardAttributeValue
  pathname?: StandardAttributeValue
  pattern?: StandardAttributeValue
  patternContentUnits?: StandardAttributeValue
  patternMismatch?: StandardAttributeValue
  patternTransform?: StandardAttributeValue
  patternUnits?: StandardAttributeValue
  pauseOnExit?: StandardAttributeValue
  paused?: StandardAttributeValue
  pdfViewerEnabled?: StandardAttributeValue
  persisted?: StandardAttributeValue
  personalbar?: StandardAttributeValue
  ping?: StandardAttributeValue
  pixelFormat?: StandardAttributeValue
  placeholder?: StandardAttributeValue
  platform?: StandardAttributeValue
  playbackRate?: StandardAttributeValue
  played?: StandardAttributeValue
  playsInline?: StandardAttributeValue
  plugins?: StandardAttributeValue
  pointerBeforeReferenceNode?: StandardAttributeValue
  points?: StandardAttributeValue
  popover?: StandardAttributeValue
  popoverTargetAction?: StandardAttributeValue
  popoverTargetElement?: StandardAttributeValue
  popovertarget?: StandardAttributeValue
  port?: StandardAttributeValue
  port1?: StandardAttributeValue
  port2?: StandardAttributeValue
  ports?: StandardAttributeValue
  position?: StandardAttributeValue
  poster?: StandardAttributeValue
  prefix?: StandardAttributeValue
  preload?: StandardAttributeValue
  preserveAspectRatio?: StandardAttributeValue
  preservesPitch?: StandardAttributeValue
  previousElementSibling?: StandardAttributeValue
  previousSibling?: StandardAttributeValue
  product?: StandardAttributeValue
  productSub?: StandardAttributeValue
  promise?: StandardAttributeValue
  protocol?: StandardAttributeValue
  publicId?: StandardAttributeValue
  r?: StandardAttributeValue
  rangeOverflow?: StandardAttributeValue
  rangeUnderflow?: StandardAttributeValue
  readOnly?: StandardAttributeValue
  readyState?: StandardAttributeValue
  reason?: StandardAttributeValue
  reasons?: StandardAttributeValue
  refX?: StandardAttributeValue
  refY?: StandardAttributeValue
  referenceNode?: StandardAttributeValue
  referrer?: StandardAttributeValue
  referrerPolicy?: StandardAttributeValue
  rel?: StandardAttributeValue
  relList?: StandardAttributeValue
  removedNodes?: StandardAttributeValue
  required?: StandardAttributeValue
  requiredExtensions?: StandardAttributeValue
  resultType?: StandardAttributeValue
  returnValue?: StandardAttributeValue
  rev?: StandardAttributeValue
  reversed?: StandardAttributeValue
  role?: StandardAttributeValue
  root?: StandardAttributeValue
  rootElement?: StandardAttributeValue
  rotate?: StandardAttributeValue
  rowIndex?: StandardAttributeValue
  rowSpan?: StandardAttributeValue
  rows?: StandardAttributeValue
  rules?: StandardAttributeValue
  rx?: StandardAttributeValue
  ry?: StandardAttributeValue
  sameDocument?: StandardAttributeValue
  sandbox?: StandardAttributeValue
  scheme?: StandardAttributeValue
  scope?: StandardAttributeValue
  scripts?: StandardAttributeValue
  scrollAmount?: StandardAttributeValue
  scrollDelay?: StandardAttributeValue
  scrollRestoration?: StandardAttributeValue
  scrollbars?: StandardAttributeValue
  scrolling?: StandardAttributeValue
  search?: StandardAttributeValue
  sectionRowIndex?: StandardAttributeValue
  seekable?: StandardAttributeValue
  seeking?: StandardAttributeValue
  selected?: StandardAttributeValue
  selectedIndex?: StandardAttributeValue
  selectedOptions?: StandardAttributeValue
  selectionDirection?: StandardAttributeValue
  selectionEnd?: StandardAttributeValue
  selectionStart?: StandardAttributeValue
  self?: StandardAttributeValue
  serializable?: StandardAttributeValue
  sessionStorage?: StandardAttributeValue
  shadowBlur?: StandardAttributeValue
  shadowColor?: StandardAttributeValue
  shadowOffsetX?: StandardAttributeValue
  shadowOffsetY?: StandardAttributeValue
  shadowRoot?: StandardAttributeValue
  shadowRootClonable?: StandardAttributeValue
  shadowRootCustomElementRegistry?: StandardAttributeValue
  shadowRootDelegatesFocus?: StandardAttributeValue
  shadowRootMode?: StandardAttributeValue
  shadowRootSerializable?: StandardAttributeValue
  shadowRootSlotAssignment?: StandardAttributeValue
  shape?: StandardAttributeValue
  signal?: StandardAttributeValue
  singleNodeValue?: StandardAttributeValue
  size?: StandardAttributeValue
  sizes?: StandardAttributeValue
  slot?: StandardAttributeValue
  slotAssignment?: StandardAttributeValue
  snapshotLength?: StandardAttributeValue
  source?: StandardAttributeValue
  sourceAnimation?: StandardAttributeValue
  sourceElement?: StandardAttributeValue
  spacing?: StandardAttributeValue
  span?: StandardAttributeValue
  specified?: StandardAttributeValue
  spellcheck?: StandardAttributeValue
  spreadMethod?: StandardAttributeValue
  src?: StandardAttributeValue
  srcElement?: StandardAttributeValue
  srcObject?: StandardAttributeValue
  srcdoc?: StandardAttributeValue
  srclang?: StandardAttributeValue
  srcset?: StandardAttributeValue
  standby?: StandardAttributeValue
  start?: StandardAttributeValue
  startContainer?: StandardAttributeValue
  startOffset?: StandardAttributeValue
  startTime?: StandardAttributeValue
  state?: StandardAttributeValue
  states?: StandardAttributeValue
  status?: StandardAttributeValue
  statusbar?: StandardAttributeValue
  step?: StandardAttributeValue
  stepMismatch?: StandardAttributeValue
  storageArea?: StandardAttributeValue
  stringValue?: StandardAttributeValue
  strokeStyle?: StandardAttributeValue
  submitter?: StandardAttributeValue
  suffixes?: StandardAttributeValue
  summary?: StandardAttributeValue
  systemId?: StandardAttributeValue
  systemLanguage?: StandardAttributeValue
  tBodies?: StandardAttributeValue
  tFoot?: StandardAttributeValue
  tHead?: StandardAttributeValue
  tabIndex?: StandardAttributeValue
  tagName?: StandardAttributeValue
  target?: StandardAttributeValue
  text?: StandardAttributeValue
  textAlign?: StandardAttributeValue
  textBaseline?: StandardAttributeValue
  textContent?: StandardAttributeValue
  textLength?: StandardAttributeValue
  textRendering?: StandardAttributeValue
  textTracks?: StandardAttributeValue
  timeStamp?: StandardAttributeValue
  title?: StandardAttributeValue
  to?: StandardAttributeValue
  tooLong?: StandardAttributeValue
  tooShort?: StandardAttributeValue
  toolbar?: StandardAttributeValue
  top?: StandardAttributeValue
  track?: StandardAttributeValue
  transform?: StandardAttributeValue
  transition?: StandardAttributeValue
  translate?: StandardAttributeValue
  trueSpeed?: StandardAttributeValue
  type?: StandardAttributeValue
  typeMismatch?: StandardAttributeValue
  types?: StandardAttributeValue
  unitType?: StandardAttributeValue
  url?: StandardAttributeValue
  useMap?: StandardAttributeValue
  userActivation?: StandardAttributeValue
  userAgent?: StandardAttributeValue
  userInitiated?: StandardAttributeValue
  username?: StandardAttributeValue
  vAlign?: StandardAttributeValue
  vLink?: StandardAttributeValue
  valid?: StandardAttributeValue
  validationMessage?: StandardAttributeValue
  validity?: StandardAttributeValue
  value?: StandardAttributeValue
  valueAsDate?: StandardAttributeValue
  valueAsNumber?: StandardAttributeValue
  valueAsString?: StandardAttributeValue
  valueInSpecifiedUnits?: StandardAttributeValue
  valueMissing?: StandardAttributeValue
  valueType?: StandardAttributeValue
  vendor?: StandardAttributeValue
  vendorSub?: StandardAttributeValue
  version?: StandardAttributeValue
  videoHeight?: StandardAttributeValue
  videoTracks?: StandardAttributeValue
  videoWidth?: StandardAttributeValue
  viewBox?: StandardAttributeValue
  viewTransition?: StandardAttributeValue
  viewportElement?: StandardAttributeValue
  visibilityState?: StandardAttributeValue
  visible?: StandardAttributeValue
  vlinkColor?: StandardAttributeValue
  volume?: StandardAttributeValue
  vspace?: StandardAttributeValue
  whatToShow?: StandardAttributeValue
  wholeText?: StandardAttributeValue
  width?: StandardAttributeValue
  willValidate?: StandardAttributeValue
  window?: StandardAttributeValue
  withCredentials?: StandardAttributeValue
  wordSpacing?: StandardAttributeValue
  wrap?: StandardAttributeValue
  writingSuggestions?: StandardAttributeValue
  x?: StandardAttributeValue
  x1?: StandardAttributeValue
  x2?: StandardAttributeValue
  y?: StandardAttributeValue
  y1?: StandardAttributeValue
  y2?: StandardAttributeValue
  [name: `data-${string}`]: StandardAttributeValue
  style?: Style
  ref?: (element: T) => void
  children?: Child
}

export type GeneratedHtml<T extends globalThis.Element> =
  GeneratedAttributes<T> & {
    onAbort?: EventHandler<UIEvent, T>
    onAnimationcancel?: EventHandler<AnimationEvent, T>
    onAnimationend?: EventHandler<AnimationEvent, T>
    onAnimationiteration?: EventHandler<AnimationEvent, T>
    onAnimationstart?: EventHandler<AnimationEvent, T>
    onAuxclick?: EventHandler<PointerEvent, T>
    onBeforeinput?: EventHandler<InputEvent, T>
    onBeforematch?: EventHandler<Event, T>
    onBeforetoggle?: EventHandler<ToggleEvent, T>
    onBlur?: EventHandler<FocusEvent, T>
    onCancel?: EventHandler<Event, T>
    onCanplay?: EventHandler<Event, T>
    onCanplaythrough?: EventHandler<Event, T>
    onChange?: EventHandler<Event, T>
    onClick?: EventHandler<PointerEvent, T>
    onClose?: EventHandler<Event, T>
    onCompositionend?: EventHandler<CompositionEvent, T>
    onCompositionstart?: EventHandler<CompositionEvent, T>
    onCompositionupdate?: EventHandler<CompositionEvent, T>
    onContextlost?: EventHandler<Event, T>
    onContextmenu?: EventHandler<PointerEvent, T>
    onContextrestored?: EventHandler<Event, T>
    onCopy?: EventHandler<ClipboardEvent, T>
    onCuechange?: EventHandler<Event, T>
    onCut?: EventHandler<ClipboardEvent, T>
    onDblClick?: EventHandler<MouseEvent, T>
    onDrag?: EventHandler<DragEvent, T>
    onDragend?: EventHandler<DragEvent, T>
    onDragenter?: EventHandler<DragEvent, T>
    onDragleave?: EventHandler<DragEvent, T>
    onDragover?: EventHandler<DragEvent, T>
    onDragstart?: EventHandler<DragEvent, T>
    onDrop?: EventHandler<DragEvent, T>
    onDurationchange?: EventHandler<Event, T>
    onEmptied?: EventHandler<Event, T>
    onEnded?: EventHandler<Event, T>
    onError?: EventHandler<ErrorEvent, T>
    onFocus?: EventHandler<FocusEvent, T>
    onFocusin?: EventHandler<FocusEvent, T>
    onFocusout?: EventHandler<FocusEvent, T>
    onFormdata?: EventHandler<FormDataEvent, T>
    onGotpointercapture?: EventHandler<PointerEvent, T>
    onInput?: EventHandler<Event, T>
    onInvalid?: EventHandler<Event, T>
    onKeydown?: EventHandler<KeyboardEvent, T>
    onKeypress?: EventHandler<KeyboardEvent, T>
    onKeyup?: EventHandler<KeyboardEvent, T>
    onLoad?: EventHandler<Event, T>
    onLoadeddata?: EventHandler<Event, T>
    onLoadedmetadata?: EventHandler<Event, T>
    onLoadstart?: EventHandler<Event, T>
    onLostpointercapture?: EventHandler<PointerEvent, T>
    onMousedown?: EventHandler<MouseEvent, T>
    onMouseenter?: EventHandler<MouseEvent, T>
    onMouseleave?: EventHandler<MouseEvent, T>
    onMousemove?: EventHandler<MouseEvent, T>
    onMouseout?: EventHandler<MouseEvent, T>
    onMouseover?: EventHandler<MouseEvent, T>
    onMouseup?: EventHandler<MouseEvent, T>
    onPaste?: EventHandler<ClipboardEvent, T>
    onPause?: EventHandler<Event, T>
    onPlay?: EventHandler<Event, T>
    onPlaying?: EventHandler<Event, T>
    onPointercancel?: EventHandler<PointerEvent, T>
    onPointerdown?: EventHandler<PointerEvent, T>
    onPointerenter?: EventHandler<PointerEvent, T>
    onPointerleave?: EventHandler<PointerEvent, T>
    onPointermove?: EventHandler<PointerEvent, T>
    onPointerout?: EventHandler<PointerEvent, T>
    onPointerover?: EventHandler<PointerEvent, T>
    onPointerrawupdate?: EventHandler<Event, T>
    onPointerup?: EventHandler<PointerEvent, T>
    onProgress?: EventHandler<ProgressEvent, T>
    onRatechange?: EventHandler<Event, T>
    onReset?: EventHandler<Event, T>
    onResize?: EventHandler<UIEvent, T>
    onScroll?: EventHandler<Event, T>
    onScrollend?: EventHandler<Event, T>
    onSecuritypolicyviolation?: EventHandler<SecurityPolicyViolationEvent, T>
    onSeeked?: EventHandler<Event, T>
    onSeeking?: EventHandler<Event, T>
    onSelect?: EventHandler<Event, T>
    onSelectionchange?: EventHandler<Event, T>
    onSelectstart?: EventHandler<Event, T>
    onSlotchange?: EventHandler<Event, T>
    onStalled?: EventHandler<Event, T>
    onSubmit?: EventHandler<SubmitEvent, T>
    onSuspend?: EventHandler<Event, T>
    onTimeupdate?: EventHandler<Event, T>
    onToggle?: EventHandler<ToggleEvent, T>
    onTouchcancel?: EventHandler<TouchEvent, T>
    onTouchend?: EventHandler<TouchEvent, T>
    onTouchmove?: EventHandler<TouchEvent, T>
    onTouchstart?: EventHandler<TouchEvent, T>
    onTransitioncancel?: EventHandler<TransitionEvent, T>
    onTransitionend?: EventHandler<TransitionEvent, T>
    onTransitionrun?: EventHandler<TransitionEvent, T>
    onTransitionstart?: EventHandler<TransitionEvent, T>
    onVolumechange?: EventHandler<Event, T>
    onWaiting?: EventHandler<Event, T>
    onWebkitanimationend?: EventHandler<Event, T>
    onWebkitanimationiteration?: EventHandler<Event, T>
    onWebkitanimationstart?: EventHandler<Event, T>
    onWebkittransitionend?: EventHandler<Event, T>
    onWheel?: EventHandler<WheelEvent, T>
  }
export type GeneratedSvg<T extends globalThis.Element> = GeneratedHtml<T>
export type GeneratedMathml<T extends globalThis.Element> = GeneratedHtml<T>

export interface GeneratedIntrinsicElements {
  a: GeneratedHtml<globalThis.HTMLAnchorElement>
  abbr: GeneratedHtml<globalThis.HTMLElement>
  acronym: GeneratedHtml<globalThis.HTMLElement>
  address: GeneratedHtml<globalThis.HTMLElement>
  annotation: GeneratedMathml<globalThis.MathMLElement>
  'annotation-xml': GeneratedMathml<globalThis.MathMLElement>
  applet: GeneratedHtml<globalThis.HTMLUnknownElement>
  area: GeneratedHtml<globalThis.HTMLAreaElement>
  article: GeneratedHtml<globalThis.HTMLElement>
  aside: GeneratedHtml<globalThis.HTMLElement>
  audio: GeneratedHtml<globalThis.HTMLAudioElement>
  b: GeneratedHtml<globalThis.HTMLElement>
  base: GeneratedHtml<globalThis.HTMLBaseElement>
  basefont: GeneratedHtml<globalThis.HTMLElement>
  bdi: GeneratedHtml<globalThis.HTMLElement>
  bdo: GeneratedHtml<globalThis.HTMLElement>
  bgsound: GeneratedHtml<globalThis.HTMLUnknownElement>
  big: GeneratedHtml<globalThis.HTMLElement>
  blink: GeneratedHtml<globalThis.HTMLUnknownElement>
  blockquote: GeneratedHtml<globalThis.HTMLQuoteElement>
  body: GeneratedHtml<globalThis.HTMLBodyElement>
  br: GeneratedHtml<globalThis.HTMLBRElement>
  button: GeneratedHtml<globalThis.HTMLButtonElement>
  canvas: GeneratedHtml<globalThis.HTMLCanvasElement>
  caption: GeneratedHtml<globalThis.HTMLTableCaptionElement>
  center: GeneratedHtml<globalThis.HTMLElement>
  circle: GeneratedSvg<globalThis.SVGCircleElement>
  cite: GeneratedHtml<globalThis.HTMLElement>
  code: GeneratedHtml<globalThis.HTMLElement>
  col: GeneratedHtml<globalThis.HTMLTableColElement>
  colgroup: GeneratedHtml<globalThis.HTMLTableColElement>
  data: GeneratedHtml<globalThis.HTMLDataElement>
  datalist: GeneratedHtml<globalThis.HTMLDataListElement>
  dd: GeneratedHtml<globalThis.HTMLElement>
  defs: GeneratedSvg<globalThis.SVGDefsElement>
  del: GeneratedHtml<globalThis.HTMLModElement>
  desc: GeneratedSvg<globalThis.SVGDescElement>
  details: GeneratedHtml<globalThis.HTMLDetailsElement>
  dfn: GeneratedHtml<globalThis.HTMLElement>
  dialog: GeneratedHtml<globalThis.HTMLDialogElement>
  dir: GeneratedHtml<globalThis.HTMLDirectoryElement>
  div: GeneratedHtml<globalThis.HTMLDivElement>
  dl: GeneratedHtml<globalThis.HTMLDListElement>
  dt: GeneratedHtml<globalThis.HTMLElement>
  ellipse: GeneratedSvg<globalThis.SVGEllipseElement>
  em: GeneratedHtml<globalThis.HTMLElement>
  embed: GeneratedHtml<globalThis.HTMLEmbedElement>
  fieldset: GeneratedHtml<globalThis.HTMLFieldSetElement>
  figcaption: GeneratedHtml<globalThis.HTMLElement>
  figure: GeneratedHtml<globalThis.HTMLElement>
  font: GeneratedHtml<globalThis.HTMLFontElement>
  footer: GeneratedHtml<globalThis.HTMLElement>
  foreignObject: GeneratedSvg<globalThis.SVGForeignObjectElement>
  form: GeneratedHtml<globalThis.HTMLFormElement>
  frame: GeneratedHtml<globalThis.HTMLFrameElement>
  frameset: GeneratedHtml<globalThis.HTMLFrameSetElement>
  g: GeneratedSvg<globalThis.SVGGElement>
  h1: GeneratedHtml<globalThis.HTMLHeadingElement>
  h2: GeneratedHtml<globalThis.HTMLHeadingElement>
  h3: GeneratedHtml<globalThis.HTMLHeadingElement>
  h4: GeneratedHtml<globalThis.HTMLHeadingElement>
  h5: GeneratedHtml<globalThis.HTMLHeadingElement>
  h6: GeneratedHtml<globalThis.HTMLHeadingElement>
  head: GeneratedHtml<globalThis.HTMLHeadElement>
  header: GeneratedHtml<globalThis.HTMLElement>
  hgroup: GeneratedHtml<globalThis.HTMLElement>
  hr: GeneratedHtml<globalThis.HTMLHRElement>
  html: GeneratedHtml<globalThis.HTMLHtmlElement>
  i: GeneratedHtml<globalThis.HTMLElement>
  iframe: GeneratedHtml<globalThis.HTMLIFrameElement>
  image: GeneratedSvg<globalThis.SVGImageElement>
  img: GeneratedHtml<globalThis.HTMLImageElement>
  input: GeneratedHtml<globalThis.HTMLInputElement>
  ins: GeneratedHtml<globalThis.HTMLModElement>
  isindex: GeneratedHtml<globalThis.HTMLUnknownElement>
  kbd: GeneratedHtml<globalThis.HTMLElement>
  keygen: GeneratedHtml<globalThis.HTMLUnknownElement>
  label: GeneratedHtml<globalThis.HTMLLabelElement>
  legend: GeneratedHtml<globalThis.HTMLLegendElement>
  li: GeneratedHtml<globalThis.HTMLLIElement>
  line: GeneratedSvg<globalThis.SVGLineElement>
  linearGradient: GeneratedSvg<globalThis.SVGLinearGradientElement>
  link: GeneratedHtml<globalThis.HTMLLinkElement>
  listing: GeneratedHtml<globalThis.HTMLPreElement>
  maction: GeneratedMathml<globalThis.MathMLElement>
  main: GeneratedHtml<globalThis.HTMLElement>
  map: GeneratedHtml<globalThis.HTMLMapElement>
  mark: GeneratedHtml<globalThis.HTMLElement>
  marker: GeneratedSvg<globalThis.SVGMarkerElement>
  marquee: GeneratedHtml<globalThis.HTMLMarqueeElement>
  math: GeneratedMathml<globalThis.MathMLElement>
  menu: GeneratedHtml<globalThis.HTMLMenuElement>
  menuitem: GeneratedHtml<globalThis.HTMLElement>
  merror: GeneratedMathml<globalThis.MathMLElement>
  meta: GeneratedHtml<globalThis.HTMLMetaElement>
  metadata: GeneratedSvg<globalThis.SVGMetadataElement>
  meter: GeneratedHtml<globalThis.HTMLMeterElement>
  mfrac: GeneratedMathml<globalThis.MathMLElement>
  mi: GeneratedMathml<globalThis.MathMLElement>
  mmultiscripts: GeneratedMathml<globalThis.MathMLElement>
  mn: GeneratedMathml<globalThis.MathMLElement>
  mo: GeneratedMathml<globalThis.MathMLElement>
  mover: GeneratedMathml<globalThis.MathMLElement>
  mpadded: GeneratedMathml<globalThis.MathMLElement>
  mphantom: GeneratedMathml<globalThis.MathMLElement>
  mprescripts: GeneratedMathml<globalThis.MathMLElement>
  mroot: GeneratedMathml<globalThis.MathMLElement>
  mrow: GeneratedMathml<globalThis.MathMLElement>
  ms: GeneratedMathml<globalThis.MathMLElement>
  mspace: GeneratedMathml<globalThis.MathMLElement>
  msqrt: GeneratedMathml<globalThis.MathMLElement>
  mstyle: GeneratedMathml<globalThis.MathMLElement>
  msub: GeneratedMathml<globalThis.MathMLElement>
  msubsup: GeneratedMathml<globalThis.MathMLElement>
  msup: GeneratedMathml<globalThis.MathMLElement>
  mtable: GeneratedMathml<globalThis.MathMLElement>
  mtd: GeneratedMathml<globalThis.MathMLElement>
  mtext: GeneratedMathml<globalThis.MathMLElement>
  mtr: GeneratedMathml<globalThis.MathMLElement>
  multicol: GeneratedHtml<globalThis.HTMLUnknownElement>
  munder: GeneratedMathml<globalThis.MathMLElement>
  munderover: GeneratedMathml<globalThis.MathMLElement>
  nav: GeneratedHtml<globalThis.HTMLElement>
  nextid: GeneratedHtml<globalThis.HTMLUnknownElement>
  nobr: GeneratedHtml<globalThis.HTMLElement>
  noembed: GeneratedHtml<globalThis.HTMLElement>
  noframes: GeneratedHtml<globalThis.HTMLElement>
  noscript: GeneratedHtml<globalThis.HTMLElement>
  object: GeneratedHtml<globalThis.HTMLObjectElement>
  ol: GeneratedHtml<globalThis.HTMLOListElement>
  optgroup: GeneratedHtml<globalThis.HTMLOptGroupElement>
  option: GeneratedHtml<globalThis.HTMLOptionElement>
  output: GeneratedHtml<globalThis.HTMLOutputElement>
  p: GeneratedHtml<globalThis.HTMLParagraphElement>
  param: GeneratedHtml<globalThis.HTMLParamElement>
  path: GeneratedSvg<globalThis.SVGPathElement>
  pattern: GeneratedSvg<globalThis.SVGPatternElement>
  picture: GeneratedHtml<globalThis.HTMLPictureElement>
  plaintext: GeneratedHtml<globalThis.HTMLElement>
  polygon: GeneratedSvg<globalThis.SVGPolygonElement>
  polyline: GeneratedSvg<globalThis.SVGPolylineElement>
  pre: GeneratedHtml<globalThis.HTMLPreElement>
  progress: GeneratedHtml<globalThis.HTMLProgressElement>
  q: GeneratedHtml<globalThis.HTMLQuoteElement>
  radialGradient: GeneratedSvg<globalThis.SVGRadialGradientElement>
  rb: GeneratedHtml<globalThis.HTMLElement>
  rect: GeneratedSvg<globalThis.SVGRectElement>
  rp: GeneratedHtml<globalThis.HTMLElement>
  rt: GeneratedHtml<globalThis.HTMLElement>
  rtc: GeneratedHtml<globalThis.HTMLElement>
  ruby: GeneratedHtml<globalThis.HTMLElement>
  s: GeneratedHtml<globalThis.HTMLElement>
  samp: GeneratedHtml<globalThis.HTMLElement>
  script: GeneratedHtml<globalThis.HTMLScriptElement>
  search: GeneratedHtml<globalThis.HTMLElement>
  section: GeneratedHtml<globalThis.HTMLElement>
  select: GeneratedHtml<globalThis.HTMLSelectElement>
  selectedcontent: GeneratedHtml<globalThis.HTMLElement>
  semantics: GeneratedMathml<globalThis.MathMLElement>
  slot: GeneratedHtml<globalThis.HTMLSlotElement>
  small: GeneratedHtml<globalThis.HTMLElement>
  source: GeneratedHtml<globalThis.HTMLSourceElement>
  spacer: GeneratedHtml<globalThis.HTMLUnknownElement>
  span: GeneratedHtml<globalThis.HTMLSpanElement>
  stop: GeneratedSvg<globalThis.SVGStopElement>
  strike: GeneratedHtml<globalThis.HTMLElement>
  strong: GeneratedHtml<globalThis.HTMLElement>
  style: GeneratedHtml<globalThis.HTMLStyleElement>
  sub: GeneratedHtml<globalThis.HTMLElement>
  summary: GeneratedHtml<globalThis.HTMLElement>
  sup: GeneratedHtml<globalThis.HTMLElement>
  svg: GeneratedSvg<globalThis.SVGSVGElement>
  switch: GeneratedSvg<globalThis.SVGSwitchElement>
  symbol: GeneratedSvg<globalThis.SVGSymbolElement>
  table: GeneratedHtml<globalThis.HTMLTableElement>
  tbody: GeneratedHtml<globalThis.HTMLTableSectionElement>
  td: GeneratedHtml<globalThis.HTMLTableCellElement>
  template: GeneratedHtml<globalThis.HTMLTemplateElement>
  text: GeneratedSvg<globalThis.SVGTextElement>
  textarea: GeneratedHtml<globalThis.HTMLTextAreaElement>
  textPath: GeneratedSvg<globalThis.SVGTextPathElement>
  tfoot: GeneratedHtml<globalThis.HTMLTableSectionElement>
  th: GeneratedHtml<globalThis.HTMLTableCellElement>
  thead: GeneratedHtml<globalThis.HTMLTableSectionElement>
  time: GeneratedHtml<globalThis.HTMLTimeElement>
  title: GeneratedHtml<globalThis.HTMLTitleElement>
  tr: GeneratedHtml<globalThis.HTMLTableRowElement>
  track: GeneratedHtml<globalThis.HTMLTrackElement>
  tspan: GeneratedSvg<globalThis.SVGTSpanElement>
  tt: GeneratedHtml<globalThis.HTMLElement>
  u: GeneratedHtml<globalThis.HTMLElement>
  ul: GeneratedHtml<globalThis.HTMLUListElement>
  use: GeneratedSvg<globalThis.SVGUseElement>
  var: GeneratedHtml<globalThis.HTMLElement>
  video: GeneratedHtml<globalThis.HTMLVideoElement>
  view: GeneratedSvg<globalThis.SVGViewElement>
  wbr: GeneratedHtml<globalThis.HTMLElement>
  xmp: GeneratedHtml<globalThis.HTMLPreElement>
}
